### ISSUE TITLE
Terms of Service & Privacy Policy

### ISSUE THREAD

**Issue by Wingysam** [Wingysam/Galaxy-Info-v2#6]
In order to verify the bot on Discord, the a webpage for the bot must include its Terms of Service and its Privacy Policy.
![image](https://github.com/Wingysam/Galaxy-Info-v2/assets/18403742/a76cfabd-b4ea-45ed-9151-6581c15b64ae)

Galaxy Info already has a Privacy Policy so that won't be an issue but I have never written a Terms of Service before. What's the best way to do that?

**Comment by BananaSplit101** [comment]
Hey there lads. I'd be interested in writing a ToS for y'all to make the bot more accessable to the community! Contact cough_drop. on discord for more (Also known as Coffee on the discord)

**Comment by SeaswimmerTheFsh** [comment]
> Contact cough_drop. on discord for more (Also known as Coffee on the discord)

@BananaSplit101, I'd prefer to keep discussions about this in this issue, so we have a record of it afterwards and so other people can chime in if they'd like to. I'm glad you're offering to help, but using Discord for this probably isn't the best idea.

**Comment by BananaSplit101** [comment]
Sure man that works as well. Just lmk some basic terms that you'd like listed. For example, Don't use the bot for [A, B, C]. It doesn't need to be anything fancy.

**Comment by BananaSplit101** [comment]
All good? @SeaswimmerTheFsh

**Comment by Wingysam** [comment]
I believe that's all we need, thank you!

**Comment by BananaSplit101** [comment]
Here's a quick draft I whipped up. Let me know what else needs done!
@SeaswimmerTheFsh @Wingysam

Terms of Service
These Terms of Service govern your access to and use of the services provided by Galaxy Info. By accessing or using our services, you agree to be bound by these Terms.
1. Acceptance of Terms
By accessing or using our services, you agree to be bound by these Terms. If you do not agree to these Terms, you may not access or use our services.
2. Use of Services
You agree to use our services only for lawful purposes and in accordance with these Terms. You may not use our services for any illegal or unauthorized purpose.
2. Limitation of Liability
In no event shall Galaxy Info be liable for any damages arising out of or in connection with your use of our services, including but not limited to direct, indirect, incidental, special, or consequential damages.
3. Changes to Terms
We reserve the right to update or modify these Terms at any time without prior notice. Your continued use of our services after any such changes constitutes your acceptance of the new Terms.
4. Contact Us
If you have any questions about these Terms, please contact us at git@wingysam.xyz

**Comment by Wingysam** [comment]
That seems good to me! I'll change the email to yname@galaxy.casa.

**Comment by SeaswimmerTheFsh** [comment]
I propose adding the following to point 2:
> We reserve the right to revoke your access to our platform at any time and for any reason, without prior warning.

**Comment by BananaSplit101** [comment]
Glad to be of help. Let me know if anything else is needed

**Comment by Wingysam** [comment]
Fixed in [d3a664d](https://github.com/Wingysam/Galaxy-Info-v2/commit/d3a664d214525cf765d335fbebd6d8926c7403e0)
